### ISSUE TITLE
KeyValueServiceGrpcKt.kt:[14,19] Unresolved reference: Generated

### ISSUE THREAD

**Issue by balzaron** [FlavioF/kotlin-grpc-sample#2]
when i compile the source code by using mvn clean install , an error raised 
"KeyValueServiceGrpcKt.kt:[14,19] Unresolved reference: Generated"
can anybody check this problem, or I have some wrong way to operate

**Comment by rouzwawi** [comment]
@balzaron This is most likely because of Java 9+ which requires you to import `javax.annotations` to the classpath.

Try adding the following to your dependencies

```xml
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```

**Comment by balzaron** [comment]
@rouzwawi  
it works! Thanks for your help!
